---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  {{- range $key, $val := .Values.tags }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- range $key, $val := .Values.frontend.deployment.annotations }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  name: {{ .Values.frontend.name }}
  labels: 
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name | quote }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.frontend.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  strategy:
    type: {{ .Values.frontend.deployment.updateStrategy.type }}
    {{- if eq .Values.frontend.deployment.updateStrategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.frontend.deployment.updateStrategy.maxSurge}}
      maxUnavailable: {{ .Values.frontend.deployment.updateStrategy.maxUnavailable}}
    {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
        release: {{ .Release.Name | quote }}
      annotations:
      {{- range $key, $val := .Values.tags }}
        {{ $key }}: {{ $val | quote }}
      {{- end }}
      {{- range $key, $value := .Values.frontend.deployment.annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    spec:
      {{- if .Values.podSecurityContext }}
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 10 }}
      {{- end }}
      {{- with .Values.frontend.deployment.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.frontend.deployment.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.frontend.deployment.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
      - image: {{ .Values.frontend.image }}:{{ .Values.codecovVersion }}
      {{- with .Values.extraEnvs }}
        env:
{{ toYaml . | nindent 10 }}
      {{- end }}
      {{- if .Values.envFrom }}
        envFrom:
{{ toYaml .Values.envFrom | indent 10 }}
      {{- end }}
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        name: {{ .Values.frontend.name }}
        ports:
        - containerPort: {{ .Values.frontend.deployment.port }}
          protocol: TCP
          name: http
        livenessProbe:
{{ toYaml .Values.frontend.deployment.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.frontend.deployment.readinessProbe | indent 10 }}
        resources:
{{ toYaml .Values.frontend.deployment.resources | indent 10 }}
        volumeMounts:
        {{- range .Values.secretMounts }}
          - name: {{ .name }}
            mountPath: {{ .path }}
            {{- if .subPath }}
            subPath: {{ .subPath }}
            {{- end }}
        {{- end }}
      restartPolicy: Always
      volumes:
      {{- range .Values.secretMounts }}
      - name: {{ .name }}
        secret:
          secretName: {{ .secretName }}
      {{- end }}
      {{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 8 }}
      {{- end }}
  {{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumeMounts | indent 10 }}
  {{- end }}
